name: keitax-net-blog

releases:
- name: airlog
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: airlog
  azs: [z1]
  instances: 2
  jobs:
  - name: airlog
    release: airlog
    properties:
      airlog:
        site_title: keitax.net Blog
        footnote: "© 2019 [Keita Mizuochi](https://twitter.com/keitax_)"
        blog_dsn: ((airlog.blog_dsn))
        github_api:
          post_repository_endpoint: https://api.github.com/repos/keitax/blog-posts
  vm_type: default
  stemcell: default
  networks:
  - name: default
