azs:
- name: z1
  cloud_properties:
    availability_zone: ap-northeast-1a

vm_types:
- name: micro
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 8000, type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 10.2.0.0/24
    gateway: 10.2.0.1
    az: z1
    cloud_properties:
      subnet: subnet-0feb5dc49b06bee62
      security_groups: [sg-077d5176b14c274be]

compilation:
  workers: 1
  reuse_compilation_vms: true
  az: z1
  vm_type: micro
  network: private
